//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.mosquitto.org.
        /// </summary>
        internal static string address_broker {
            get {
                return ResourceManager.GetString("address_broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Click.
        /// </summary>
        internal static string caption_button {
            get {
                return ResourceManager.GetString("caption_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optel.
        /// </summary>
        internal static string caption_windown {
            get {
                return ResourceManager.GetString("caption_windown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsForms10.BUTTON.app.0.141b42a_r7_ad1.
        /// </summary>
        internal static string class_button {
            get {
                return ResourceManager.GetString("class_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsForms10.EDIT.app.0.141b42a_r7_ad1.
        /// </summary>
        internal static string class_textbox {
            get {
                return ResourceManager.GetString("class_textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1883.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vule/projects/monitor.
        /// </summary>
        internal static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
    }
}
